apiVersion: v1
kind: Service
metadata:
  name: prometheus-dingtalk-hook
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prometheus-dingtalk-hook
  ports:
    - name: http
      port: 9098
      targetPort: http
      protocol: TCP
